export const channels: any = {
    'id': '1537705453613',
    'jsonrpc': '2.0',
    'result':
    {
        'channels': [
        {
            'broadcastnow':
            {
                'broadcastid': 511695,
                'cast': '',
                'director': '',
                'endtime': '2018-09-23 13:00:00',
                'episodename': 'Fernsehfilm Deutschland 2011',
                'episodenum': 0,
                'episodepart': 0,
                'filenameandpath': 'pvr://guide/-001/2018-09-23 11:30:00.epg',
                'firstaired': '1970-01-01',
                'genre': ['Film', 'Drama'],
                'hasrecording': false,
                'hastimer': false,
                'hastimerrule': false,
                'imdbnumber': '',
                'isactive': true,
                'isseries': false,
                'originaltitle': '',
                'parentalrating': 0,
                'plot': 'Sie sind seit der Schulzeit beste Freundinnen:',
                'plotoutline': 'Fernsehfilm Deutschland 2011',
                'progress': 3253,
                'progresspercentage': 60.240741729736328125,
                'rating': 0,
                'recording': '',
                'runtime': 90,
                'starttime': '2018-09-23 11:30:00',
                'title': 'Das Gl�ck ist ein Kaktus',
                'wasactive': false,
                'writer': '',
                'year': 0
            },
            'channel': 'Das Erste HD',
            'channelid': 518,
            'channeltype': 'tv',
            'hidden': false,
            'isrecording': false,
            'label': 'Das Erste HD',
            'lastplayed': '2018-09-22',
            'locked': false,
            'thumbnail': 'image://http%3a%2f%2fosmc%3aosmc%40127.0.0.1%3a9981%2f1_0_19_283D_3FB_1_FFFF0000_0_0_0.png/'
        },
        {
            'broadcastnow':
            {
                'broadcastid': 557953,
                'cast': '',
                'director': '',
                'endtime': '2018-09-23 12:30:00',
                'episodename': '',
                'episodenum': 0,
                'episodepart': 0,
                'filenameandpath': 'pvr://guide/-001/2018-09-23 11:45:00.epg',
                'firstaired': '1970-01-01',
                'genre': ['Sozial/Politisch/Wirtschaft'],
                'hasrecording': false,
                'hastimer': false,
                'hastimerrule': false,
                'imdbnumber': '',
                'isactive': true,
                'isseries': false,
                'originaltitle': '',
                'parentalrating': 0,
                'plot': 'Factual Entertainment, Deutschland 2018',
                'plotoutline': '',
                'progress': 2353,
                'progresspercentage': 87.1481475830078125,
                'rating': 0,
                'recording': '',
                'runtime': 45,
                'starttime': '2018-09-23 11:45:00',
                'title': '3 Pl�ne f�r mein sch�nstes Zimmer',
                'wasactive': false,
                'writer': '',
                'year': 0
            },
            'channel': 'ZDF HD',
            'channelid': 486,
            'channeltype': 'tv',
            'hidden': false,
            'isrecording': false,
            'label': 'ZDF HD',
            'lastplayed': '1970-01-01',
            'locked': false,
            'thumbnail': 'image://http%3a%2f%2fosmc%3aosmc%40127.0.0.1%3a9981%2f1_0_19_2B66_3F3_1_FFFF0000_0_0_0.png/'
        },
        {
            'broadcastnow':
            {
                'broadcastid': 511635,
                'cast': '',
                'director': '',
                'endtime': '2018-09-23 14:00:00',
                'episodename': '',
                'episodenum': 0,
                'episodepart': 0,
                'filenameandpath': 'pvr://guide/-001/2018-09-23 11:45:00.epg',
                'firstaired': '1970-01-01',
                'genre': ['Soap', 'Melodrama', 'Folkore'],
                'hasrecording': false,
                'hastimer': false,
                'hastimerrule': false,
                'imdbnumber': '',
                'isactive': true,
                'isseries': false,
                'originaltitle': '',
                'parentalrating': 0,
                'plot': 'Seit 1949 treten die Weinhoheiten',
                'plotoutline': '',
                'progress': 2353,
                'progresspercentage': 29.049383163452148438,
                'rating': 0,
                'recording': '',
                'runtime': 135,
                'starttime': '2018-09-23 11:45:00',
                'title': 'Wahl der Deutschen Weink�nigin - Die Vorentscheidung',
                'wasactive': false,
                'writer': '',
                'year': 0
            },
            'channel': 'SWR BW HD',
            'channelid': 512,
            'channeltype': 'tv',
            'hidden': false,
            'isrecording': false,
            'label': 'SWR BW HD',
            'lastplayed': '2017-05-13',
            'locked': false,
            'thumbnail': 'image://http%3a%2f%2fosmc%3aosmc%40127.0.0.1%3a9981%2f1_0_19_283F_3FB_1_FFFF0000_0_0_0.png/'
        },
        {
            'broadcastnow':
            {
                'broadcastid': 576205,
                'cast': '',
                'director': '',
                'endtime': '2018-09-23 12:30:00',
                'episodename': 'Waltraud und Mariechen auf der Wiesn',
                'episodenum': 0,
                'episodepart': 0,
                'filenameandpath': 'pvr://guide/-001/2018-09-23 12:00:00.epg',
                'firstaired': '1970-01-01',
                'genre': ['Soap', 'Melodrama', 'Folkore'],
                'hasrecording': false,
                'hastimer': false,
                'hastimerrule': false,
                'imdbnumber': '',
                'isactive': true,
                'isseries': false,
                'originaltitle': '',
                'parentalrating': 0,
                'plot': 'Waltraud und Mariechen machen diesmal',
                'plotoutline': 'Waltraud und Mariechen auf der Wiesn',
                'progress': 1453,
                'progresspercentage': 80.72222137451171875,
                'rating': 0,
                'recording': '',
                'runtime': 30,
                'starttime': '2018-09-23 12:00:00',
                'title': 'Hei�mann + Rassau',
                'wasactive': false,
                'writer': '',
                'year': 0
            },
            'channel': 'BR Fernsehen S�d HD',
            'channelid': 493,
            'channeltype': 'tv',
            'hidden': false,
            'isrecording': false,
            'label': 'BR Fernsehen S�d HD',
            'lastplayed': '2017-05-13',
            'locked': false,
            'thumbnail': 'image://http%3a%2f%2fosmc%3aosmc%40127.0.0.1%3a9981%2f1_0_19_2855_401_1_FFFF0000_0_0_0.png/'
        },
        {
            'channel': 'REGIO TV HD',
            'channelid': 498,
            'channeltype': 'tv',
            'hidden': false,
            'isrecording': false,
            'label': 'REGIO TV HD',
            'lastplayed': '1970-01-01',
            'locked': false,
            'thumbnail': 'image://http%3a%2f%2fosmc%3aosmc%40127.0.0.1%3a9981%2f1_0_16_13BA_41A_2B67_FFFF0000_0_0_0.png/'
        },
        {
            'broadcastnow':
            {
                'broadcastid': 532549,
                'cast': '',
                'director': '',
                'endtime': '2018-09-23 12:56:50',
                'episodename': 'Sport, D 2018',
                'episodenum': 0,
                'episodepart': 0,
                'filenameandpath': 'pvr://guide/-001/2018-09-23 10:59:59.epg',
                'firstaired': '1970-01-01',
                'genre': ['Andere', 'Unbekannt'],
                'hasrecording': false,
                'hastimer': false,
                'hastimerrule': false,
                'imdbnumber': '',
                'isactive': true,
                'isseries': false,
                'originaltitle': '',
                'parentalrating': 0,
                'plot': 'Moderation: Andrea Kaiser',
                'plotoutline': 'Sport, D 2018',
                'progress': 5054,
                'progresspercentage': 72.08672332763671875,
                'rating': 0,
                'recording': '',
                'runtime': 116,
                'starttime': '2018-09-23 10:59:59',
                'title': 'ran racing: DTM 2018 live aus Spielberg',
                'wasactive': false,
                'writer': '',
                'year': 0
            },
            'channel': 'SAT.1',
            'channelid': 511,
            'channeltype': 'tv',
            'hidden': false,
            'isrecording': false,
            'label': 'SAT.1',
            'lastplayed': '2018-09-22',
            'locked': false,
            'thumbnail': 'image://http%3a%2f%2fosmc%3aosmc%40127.0.0.1%3a9981%2f1_0_1_406_3F1_2B67_FFFF0000_0_0_0.png/'
        },
        {
            'broadcastnow':
            {
                'broadcastid': 533807,
                'cast': '',
                'director': '',
                'endtime': '2018-09-23 13:53:20',
                'episodename': 'Kom�die, USA 2010',
                'episodenum': 0,
                'episodepart': 0,
                'filenameandpath': 'pvr://guide/-001/2018-09-23 12:21:01.epg',
                'firstaired': '1970-01-01',
                'genre': ['Andere', 'Unbekannt'],
                'hasrecording': false,
                'hastimer': false,
                'hastimerrule': false,
                'imdbnumber': '',
                'isactive': true,
                'isseries': false,
                'originaltitle': '',
                'parentalrating': 0,
                'plot': 'Becca Crane zieht nach Sporks zu',
                'plotoutline': 'Kom�die, USA 2010',
                'progress': 192,
                'progresspercentage': 3.4663295745849609375,
                'rating': 0,
                'recording': '',
                'runtime': 92,
                'starttime': '2018-09-23 12:21:01',
                'title': 'Beilight - Biss zum Abendbrot',
                'wasactive': false,
                'writer': '',
                'year': 0
            },
            'channel': 'ProSieben',
            'channelid': 476,
            'channeltype': 'tv',
            'hidden': false,
            'isrecording': false,
            'label': 'ProSieben',
            'lastplayed': '2018-09-22',
            'locked': false,
            'thumbnail': 'image://http%3a%2f%2fosmc%3aosmc%40127.0.0.1%3a9981%2f1_0_1_3FC_3F1_2B67_FFFF0000_0_0_0.png/'
        }],
        'limits':
        {
            'end': 52,
            'start': 0,
            'total': 52
        }
    }
};
