export const channel: any = {
    'id': '1537710221465',
    'jsonrpc': '2.0',
    'result':
    {
        'broadcasts': [
        {
            'broadcastid': 517659,
            'cast': '',
            'director': '',
            'endtime': '2018-09-22 21:40:00',
            'episodename': 'spricht Pastorin Annette Behnken, Loccum',
            'episodenum': 0,
            'episodepart': 0,
            'firstaired': '1970-01-01',
            'genre': ['Kunst', 'Kultur'],
            'hasrecording': false,
            'hastimer': false,
            'hastimerrule': false,
            'imdbnumber': '',
            'isactive': false,
            'isseries': false,
            'label': 'Das Wort zum Sonntag',
            'originaltitle': '',
            'parentalrating': 0,
            'plot': 'Pastorin Annette Behnken spricht �ber die Bef�rderung des ehemaligen Pr�sidenten des Verfassungsschutzes Hans-Georg Maa�en und �ber Demut.',
            'plotoutline': 'spricht Pastorin Annette Behnken, Loccum',
            'progress': 58121,
            'progresspercentage': 100.0,
            'rating': 0,
            'recording': '',
            'runtime': 5,
            'starttime': '2018-09-22 21:35:00',
            'thumbnail': '',
            'title': 'Das Wort zum Sonntag',
            'wasactive': true,
            'writer': '',
            'year': 0
        },
        {
            'broadcastid': 517661,
            'cast': '',
            'director': '',
            'endtime': '2018-09-22 23:10:00',
            'episodename': 'Spielfilm USA / Gro�britannien 2012 (Lay the Favorite)',
            'episodenum': 0,
            'episodepart': 0,
            'firstaired': '1970-01-01',
            'genre': ['Film', 'Drama'],
            'hasrecording': false,
            'hastimer': false,
            'hastimerrule': false,
            'imdbnumber': '',
            'isactive': false,
            'isseries': false,
            'label': 'Lady Vegas',
            'originaltitle': '',
            'parentalrating': 0,
            'plot': 'Die junge Beth hat die Nase voll',
            'plotoutline': 'Spielfilm USA / Gro�britannien 2012 (Lay the Favorite)',
            'progress': 57821,
            'progresspercentage': 100.0,
            'rating': 0,
            'recording': '',
            'runtime': 90,
            'starttime': '2018-09-22 21:40:00',
            'thumbnail': '',
            'title': 'Lady Vegas',
            'wasactive': true,
            'writer': '',
            'year': 0
        },
        {
            'broadcastid': 517663,
            'cast': '',
            'director': '',
            'endtime': '2018-09-22 23:15:00',
            'episodename': '',
            'episodenum': 0,
            'episodepart': 0,
            'firstaired': '1970-01-01',
            'genre': ['Nachrichten', 'Tagesgeschehen'],
            'hasrecording': false,
            'hastimer': false,
            'hastimerrule': false,
            'imdbnumber': '',
            'isactive': false,
            'isseries': false,
            'label': 'Tagesschau',
            'originaltitle': '',
            'parentalrating': 0,
            'plot': 'Die Nachrichten der ARD',
            'plotoutline': '',
            'progress': 52421,
            'progresspercentage': 100.0,
            'rating': 0,
            'recording': '',
            'runtime': 5,
            'starttime': '2018-09-22 23:10:00',
            'thumbnail': '',
            'title': 'Tagesschau',
            'wasactive': true,
            'writer': '',
            'year': 0
        },
        {
            'broadcastid': 517665,
            'cast': '',
            'director': '',
            'endtime': '2018-09-23 00:53:00',
            'episodename': 'Spielfilm USA 1988 (Married to the Mob)',
            'episodenum': 0,
            'episodepart': 0,
            'firstaired': '1970-01-01',
            'genre': ['Film', 'Drama'],
            'hasrecording': false,
            'hastimer': false,
            'hastimerrule': false,
            'imdbnumber': '',
            'isactive': false,
            'isseries': false,
            'label': 'Die Mafiosi-Braut',
            'originaltitle': '',
            'parentalrating': 0,
            'plot': 'Die sch�ne Angela f�hrt als',
            'plotoutline': 'Spielfilm USA 1988 (Married to the Mob)',
            'progress': 52121,
            'progresspercentage': 100.0,
            'rating': 0,
            'recording': '',
            'runtime': 98,
            'starttime': '2018-09-22 23:15:00',
            'thumbnail': '',
            'title': 'Die Mafiosi-Braut',
            'wasactive': true,
            'writer': '',
            'year': 0
        },
        {
            'broadcastid': 517783,
            'cast': '',
            'director': '',
            'endtime': '2018-09-23 00:55:00',
            'episodename': '',
            'episodenum': 0,
            'episodepart': 0,
            'firstaired': '1970-01-01',
            'genre': ['Nachrichten', 'Tagesgeschehen'],
            'hasrecording': false,
            'hastimer': false,
            'hastimerrule': false,
            'imdbnumber': '',
            'isactive': false,
            'isseries': false,
            'label': 'Tagesschau',
            'originaltitle': '',
            'parentalrating': 0,
            'plot': 'Die Nachrichten der ARD',
            'plotoutline': '',
            'progress': 46241,
            'progresspercentage': 100.0,
            'rating': 0,
            'recording': '',
            'runtime': 2,
            'starttime': '2018-09-23 00:53:00',
            'thumbnail': '',
            'title': 'Tagesschau',
            'wasactive': true,
            'writer': '',
            'year': 0
        },
        {
            'broadcastid': 517785,
            'cast': '',
            'director': '',
            'endtime': '2018-09-23 02:25:00',
            'episodename': 'Spielfilm USA / Gro�britannien 2012 (Lay the Favorite)',
            'episodenum': 0,
            'episodepart': 0,
            'firstaired': '1970-01-01',
            'genre': ['Film', 'Drama'],
            'hasrecording': false,
            'hastimer': false,
            'hastimerrule': false,
            'imdbnumber': '',
            'isactive': false,
            'isseries': false,
            'label': 'Lady Vegas',
            'originaltitle': '',
            'parentalrating': 0,
            'plot': 'Die junge Beth hat die Nase',
            'plotoutline': 'Spielfilm USA / Gro�britannien 2012 (Lay the Favorite)',
            'progress': 46121,
            'progresspercentage': 100.0,
            'rating': 0,
            'recording': '',
            'runtime': 90,
            'starttime': '2018-09-23 00:55:00',
            'thumbnail': '',
            'title': 'Lady Vegas',
            'wasactive': true,
            'writer': '',
            'year': 0
        },
        {
            'broadcastid': 517787,
            'cast': '',
            'director': '',
            'endtime': '2018-09-23 02:58:00',
            'episodename': 'Eine Stadt ohne Plastik',
            'episodenum': 0,
            'episodepart': 0,
            'firstaired': '1970-01-01',
            'genre': ['Nachrichten', 'Tagesgeschehen'],
            'hasrecording': false,
            'hastimer': false,
            'hastimerrule': false,
            'imdbnumber': '',
            'isactive': false,
            'isseries': false,
            'label': 'Weltspiegel-Reportage: Cornwall',
            'originaltitle': '',
            'parentalrating': 0,
            'plot': 'Umgeben von atemberaubenden Steilklippen',
            'plotoutline': 'Eine Stadt ohne Plastik',
            'progress': 40721,
            'progresspercentage': 100.0,
            'rating': 0,
            'recording': '',
            'runtime': 33,
            'starttime': '2018-09-23 02:25:00',
            'thumbnail': '',
            'title': 'Weltspiegel-Reportage: Cornwall',
            'wasactive': true,
            'writer': '',
            'year': 0
        },
        {
            'broadcastid': 517789,
            'cast': '',
            'director': '',
            'endtime': '2018-09-23 03:00:00',
            'episodename': '',
            'episodenum': 0,
            'episodepart': 0,
            'firstaired': '1970-01-01',
            'genre': ['Nachrichten', 'Tagesgeschehen'],
            'hasrecording': false,
            'hastimer': false,
            'hastimerrule': false,
            'imdbnumber': '',
            'isactive': false,
            'isseries': false,
            'label': 'Tagesschau',
            'originaltitle': '',
            'parentalrating': 0,
            'plot': 'Die Nachrichten der ARD',
            'plotoutline': '',
            'progress': 38741,
            'progresspercentage': 100.0,
            'rating': 0,
            'recording': '',
            'runtime': 2,
            'starttime': '2018-09-23 02:58:00',
            'thumbnail': '',
            'title': 'Tagesschau',
            'wasactive': true,
            'writer': '',
            'year': 0
        },
        {
            'broadcastid': 511311,
            'cast': '',
            'director': '',
            'endtime': '2018-09-23 03:30:00',
            'episodename': '',
            'episodenum': 0,
            'episodepart': 0,
            'firstaired': '1970-01-01',
            'genre': ['Nachrichten', 'Tagesgeschehen'],
            'hasrecording': false,
            'hastimer': false,
            'hastimerrule': false,
            'imdbnumber': '',
            'isactive': false,
            'isseries': false,
            'label': 'Brisant',
            'originaltitle': '',
            'parentalrating': 0,
            'plot': 'Tr�ume und Trag�dien, menschliche und tierische Schicksale liefern den Stoff',
            'plotoutline': '',
            'progress': 38621,
            'progresspercentage': 100.0,
            'rating': 0,
            'recording': '',
            'runtime': 30,
            'starttime': '2018-09-23 03:00:00',
            'thumbnail': '',
            'title': 'Brisant',
            'wasactive': true,
            'writer': '',
            'year': 0
        },
        {
            'broadcastid': 511313,
            'cast': '',
            'director': '',
            'endtime': '2018-09-23 03:55:00',
            'episodename': 'Wie kommt das Salz in die Suppe?',
            'episodenum': 0,
            'episodepart': 0,
            'firstaired': '1970-01-01',
            'genre': ['Kinder-', 'Jugendprogramm'],
            'hasrecording': false,
            'hastimer': false,
            'hastimerrule': false,
            'imdbnumber': '',
            'isactive': false,
            'isseries': false,
            'label': 'Willi wills wissen',
            'originaltitle': '',
            'parentalrating': 0,
            'plot': 'Willi kocht sein',
            'plotoutline': 'Wie kommt das Salz in die Suppe?',
            'progress': 36821,
            'progresspercentage': 100.0,
            'rating': 0,
            'recording': '',
            'runtime': 25,
            'starttime': '2018-09-23 03:30:00',
            'thumbnail': '',
            'title': 'Willi wills wissen',
            'wasactive': true,
            'writer': '',
            'year': 0
        },
        {
            'broadcastid': 511315,
            'cast': '',
            'director': '',
            'endtime': '2018-09-23 04:20:00',
            'episodename': 'Frankenlumpi',
            'episodenum': 0,
            'episodepart': 0,
            'firstaired': '1970-01-01',
            'genre': ['Kinder-', 'Jugendprogramm'],
            'hasrecording': false,
            'hastimer': false,
            'hastimerrule': false,
            'imdbnumber': '',
            'isactive': false,
            'isseries': false,
            'label': 'Wissen macht Ah!',
            'originaltitle': '',
            'parentalrating': 0,
            'plot': 'Shary und Ralph gruselt es heute: Mit Licht und einer Lupe erzeugen sie ziemlich unheimliche Effekte.',
            'plotoutline': 'Frankenlumpi',
            'progress': 35321,
            'progresspercentage': 100.0,
            'rating': 0,
            'recording': '',
            'runtime': 25,
            'starttime': '2018-09-23 03:55:00',
            'thumbnail': '',
            'title': 'Wissen macht Ah!',
            'wasactive': true,
            'writer': '',
            'year': 0
        }],
        'limits':
        {
            'end': 185,
            'start': 0,
            'total': 185
        }
    }
};
